@extends('layouts.frontend')

@section("title","Legal")

@section('content')
	<style>
		.legal-page{
			background: #fff;
		}
		.legal-page > h1{
			font-size: 24px;
			font-weight: 700;
		}
		.legal-page h2{
			font-size: 20px;
		}
		.legal-page .page-header {
		    background: #fff;
		    text-align: center;
		    color: #039be5;
		    border-bottom: none;
		    font-size: 23px;
		    font-weight: bold;
		    margin-bottom: 25px;
		}
		
	</style>
	<div class="container legal-page">
	<h2 class="page-header test-homula1">Legal</h2>

    <h1>TERMS AND CONDITIONS</h1>
    <p>Homula provides information on real estate issues in Ontario Canada ranging from residential to commercial properties. By enlisting the services of Homula, you agree to the terms and conditions of our services. All guidelines and regulations are put in place to improve our service to our customers. These terms and conditions are subject to regular review and update as we deem best. All changes and updates are updated on our website within 24 hours of updating them.</p>
    <p>The terms of our services are clearly outlined and simplified to make it easy for clients to understand and for us to be able to best assist in addressing any concerns and questions from clients.</p>
    <h2>SERVICES</h2>
    <p>All services offered by Homula are subject to these terms and conditions. Through Homula you can subscribe to alerts and access all information pertaining to real estate properties, agents, brokers and sales persons this includes information on companies that we work together with and all our sponsors.</p>
    <h2>CUSTOMER CARE</h2>
    <p>Our customer care services are available to our clients every day through our hotline numbers, email, and social media sites. Our customer care agents are expected to serve and address any concerns raised by clients. They offer assistance on how to go about our services. We are however opposed to customers who use these contact means abusively. We reserve the right to discontinue a customer’s access to our services if we determine that the customer has been disrespectful and abusive to our customer care agents.</p>
    <h2>PRIVACY POLICY</h2>
    <p>Homula respects the privacy of customers and ensures that all personal details are protected from access by any other parties. All our clients ensure that they opt out of third party tools. In the case that they do not, they allow for access to their personal information by third parties and Homula is not liable for that.</p>
    <p>All websites utilize Internet Protocol (IP) addresses to study a user’s patterns and trends. This information is, however, safe and cannot lead to access of client information. We retain all information on clients that is provided to us through our cookies and beacons. </p>
    <p>Once you agree to our terms, you allow us to use your information in the case of any requirement by law without informing you. You give us the right to participate in protecting your legal interests. We can amend our privacy terms through an understanding with you. In the case of participation in any promotional services by us, special terms apply where you agree to the terms by clicking on the I agree button.</p>
    <h2>REPRESENTATION</h2>
    <p>Our terms clearly state that to enlist our services, you must be at least 18 years of age which is the legal age allowing anyone to enter into binding contracts. Parental advice is required for those under 18 years. </p>
    <h2>OUR RIGHTS</h2>
    <p>We retain or hold no ownership claim to any of your information or content that you have submitted to us. You retain ownership of the patent, trademark and copyright rights, and it is your responsibility to protect your work. By sharing your content with us, you, however, allow us to display your information, reproduce and modify it as we see fit to help in promoting our services. We also have the right to reject any content unfit to be displayed on our website. You warrant that you have all the authority to grant the conditions set in this section all content submitted.</p>
    <p>Homula does not control content generated by users and us, therefore, cannot guarantee the quality and credibility of this information. Any errors and misinformation are the responsibility of the author of this information.</p>
    <h2>CUSTOMER RIGHTS</h2>
    <p>We retain or hold no ownership claim to any of your information or content that you have submitted to us. You retain ownership of the patent, trademark and copyright rights and it is your responsibility to protect your work. By sharing your content with us, you however, allow us to display your information, reproduce and modify it as we see fit to help in promoting our services. We also have the right to reject any content unfit to be displayed on our website. You warrant that you have all the authority to grant the conditions set in this section all content submitted.</p>
    <p>Homula does not control content generated by users and therefore cannot guarantee the quality and credibility of this information. Any errors and misinformation are the responsibility of the author of this information.</p>
    <h2>CONDUCT</h2>
    <p>Any material that you produce in the form of text, picture, video, email and graphics and provide to Homula is your responsibility and you are held responsible for that material. You also agree that you enlist our services at your risk as we do not in any way or form have an obligation to flag, filter and screen content available through our services. If you are exposed to objective and indecent content, we are not held responsible for that.</p>
    <p>Homula is not responsible for client behavior, any consequences arising from your behavior are your sole responsibility. Agreeing to our terms requires you to use our services in a proper manner and with respect to all applicable policies. You are not to interfere with the normal order of service. Homula reserves the right to draw up and alter additional policies to regulate your use of some of our services.</p>
    <h2>INTERRUPTION OF SERVICES</h2>
    <p>We can at any time of our choosing prevent access to all or part of our services for the purpose of modification of our services. We are not to be held liable for our right to conduct this exercise. Through our terms, you agree that we do not guarantee uninterrupted and secure access to our services at all times. You agree that your use of our services can be affected by unavoidable circumstances.</p>
    <h2>PROHIBITED ACTIVITIES</h2>
    <p>You agree and understand that you cannot use our services to:
        <br> I. Disregard any patent, trademark, trade secret, copyright, the right of publicity or other rights.
        <br> II. Reproduce, copy, sell, data mining for any commercial gain of our services and content.
        <br> III. Violate any national or international laws
        <br> IV. Access personal data of other users for any intent
        <br> V. Circulate any unlawful content that could defame anyone or is objective, racist, threatening or indecent.
        <br> VI. Misrepresentation by impersonating any of our personnel
        <br> VII. Offer assistance to anyone breaking any of our terms
        <br> VIII. Interfering with users ability to gain access to our services and enjoy these services
        <br> IX. Embed material aimed at disrupting the display of information on our website like a pop-up window covering our display.
        <br> X. Support the transmission of spam messages to our clients via email or any other means</p>
    <h2>TERMINATION</h2>
    <p>You can terminate all your accounts with us at any time without prior notice to Homula. You have free reign over your account. Once you terminate your account, your access to our services is also terminated. All terms that applied to you for owning the account cease to apply to you and your account.</p>
    <h2>LICENSING</h2>
    <p>The License Agreement a single login. The license is given to a single user or group of users for Multiple User Licenses and Site Licenses. It requires that each user has a license, either solely or as a group. A Multi-User License allows the access to a specific number of users at any given time. There is a licensing fee that can be increased if one orders additional use across multiple URLs.</p>
    <p>The license and our terms do not permit you to do the following:
        <br> a. Alter, distribute or transfer licensed content
        <br> b. Sell or sublicense already licensed content
        <br> You expressly agree to protect all licensed content from being copied, distributed and accessed by any unauthorized third parties. Use of bots or any automated software that can be used to mine data is prohibited, and if any of these requirements are broken, we have the right to block your access to our services and terminate your account.</p>
    <p>Agreeing to our terms and conditions, you understand that you cannot embed spyware or any viruses into our servers.</p>
    <h2>MULTIPLE LISTING SERVICES</h2>
    <p>You understand and consent that your use of these services is subject to the terms and conditions set by MLS suppliers and that you must be a registered member. All fees required for the MLS data services is your responsibility. We are to retain all signed contracts and do not necessarily have to grant access to the final MLS contract. You allow access and use of MLS data services by third parties at your own risk. </p>
    <p>After activation of the MLS account and confirmation of credentials, our service fee is applied through billing your credit card. A monthly charged is to be applied for as long as the account is active. Once you cancel your account, inform us immediately so that we can discontinue the monthly charge. We are not liable for failure to properly notify of an account cancellation and will not be obligated to give refunds. There are no account cancellation fees applied by Homula.</p>
    <h2>DISCLAIMER</h2>
    <p>DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY TO THE FULLEST EXTENT PERMITTED BY LAW AND OTHER RELATED ENTITIES, SERVICE PROVIDERS, LICENSORS, AND RESPECTIVE OFFICERS, DIRECTORS, AGENTS, EXPRESSLY DISCLAIM ALL KINDS OF WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ALL IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, RELATED TO OUR SERVICES. YOU UNDERSTAND AND CONCENT THAT YOUR USE OF OUR SERVICES IS AT YOUR OWN RISK. OUR SERVICES AND PRODUCTS, OFFERED THROUGH THE SITE ARE PROVIDED ON AN “AS IS” BASIS. HOMULA AND OUR PARTNERS ARE NOT RESPONSIBLE FOR THE TIMELINESS OF DELIVERY OF CONTENT, ANY FAILURES OF DELIVERY, DELETION, OR ANY DAMAGE OF ANY KIND YOU CLAIM WAS CAUSED BY THE USE OF OUR SERVICES. WE DO NOT GUARANTEE UNINTERRUPTED AND SECURE ACCESS TO OUR SERVICES AT ALL TIMES
        <br> ANY MATERIAL THAT YOU DOWNLOAD FROM US IS AT YOUR SOLE DISCRETION AND YOU ARE RESPONSIBLE FOR ANY DAMAGE THAT MAY BE DONE TO YOUR COMPUTER. ANY ADVICE GIVEN TO YOU BY US IS NOT A WARRANTY THAT WE CAN BE HELD LEGIBLE FOR.
        <br> YOU AGREE THAT WE ARE NOT LIABLE FOR ANY SPECIAL OR CONSEQUENTIAL DAMAGES INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS RESULTING FROM THE USE OF HOMULA, UNAUTHORIZED ACCESS TO YOUR DATA AND ANY OTHER ISSUE DIRECTLY LINKED TO OUR SERVICES.
        <br> WE DO NOT OMIT OR LIMIT ANY LIABILITY OR RIGHT THAT ARE NOT LAWFUL. THE EXCLUSION OF CERTAIN WARRANTIES IS NOT ENCOURAGED BY CERTAIN JURISDICTIONS FOR BREACH OF CONTRACT AND INCIDENTAL DAMAGES. SOME LIMITATIONS IN THE DISCLAIMER MAY HOWEVER NOT APPLY TO YOU
        <br> • OTHER TERMS</p>
    <p>These Terms are binding to each party and its successors. Terms of this service are not transferable without written consent by us. You understand that in the event of a merger, these terms of agreement assigned through us to a third party.
        <br> All Terms contain the complete understanding of the parties regarding the subject matter and are above all other agreements and understandings that may have been drawn earlier Delays of any parties in exercising their rights and privilege under these Terms serves as a waiver, and no single or partial exercise of any right and privilege includes any other exercise of any other such right, or privilege.</p>
    <p>Should parts of these terms of these services be considered invalid and unlawful, all other parts are not to be affected and remain valid. The invalid section is revised and modified accordingly to make it lawful.</p>
    <p>All complaints and concerns that may arise from the use of our services and these terms of service must be filed within one year of the claim after which the period is expired and the claim no longer actionable.</p>
    <p>All costs and fees owed to attorneys and expert witnesses are to be settled under this term of service.We are not to be held liable for any failure or interference that is beyond our control such as internet failure, insufficiency of the network by service providers and any other natural disaster.</p>

    </div>
   
@endsection
